plugins:
 - babel
env:
  es6: true
  node: true
parser: babel-eslint
extends: 
 - 'airbnb-base'
 - 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
 no-console: 0
